 name 			= "Komodo Platoon Commander";                     // Name of your mod
 author 		= "Jellyfish (Original code), Komodo (New design), Tally (New code)"; // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "[k].paa";                                // Logo displayed in the main menu
 logoOver 		= "[k].paa";                                // When the mouse is over, in the main menu
 tooltip 		= "Komodo Platoon Commander";
 tooltipOwned 	= "credit_mod";                             // Tool tip displayed when the mouse is left over, in the main menu
 picture 		= "[k].jpg";                                // Picture displayed from the expansions menu. Optimal size is 2048x1024
 actionName 	= "Discord";                                // Button-text
 action 		= "https://discord.gg/bRTqWJzeza";          // Website URL, that can be accessed from the expansions menu
 overview 		= "An edited version of Platoon Commander"; // Supports structured text
 hideName 		= 0;                                        // Hide the extension name
 hidePicture	= 0;	                                    // Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30,1};                       // Color used for DLC stripes and backgrounds (RGBA)
 logoSmall 		= "[k].jpg";                                // Display in creative lists, next to the entities added by the mod